apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: utils-task
spec:
  description: >-
    Utilities
  params:
    - name: SCRIPT
      description: Run a Script
      default: "echo no-script-passed"
  workspaces:
    - name: source
      optional: true
  steps:
    - name: script
      image: appstudio-utils
      script: |
        { set +x ;} 2> /dev/null
        echo "App Studio Utility Task $(context.task.name)"
        { set +x ;} 2> /dev/null
        echo "$(params.SCRIPT)" | bash
