apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "image-build, hacbs"
  name: prefetch-dependencies
spec:
  description: |-
    Task that uses Cachi2 to prefetch build dependencies.
    See docs at https://github.com/containerbuildsystem/cachi2#basic-usage.
  params:
  - description: Configures project packages that will have their dependencies prefetched.
    name: input
  steps:
  - image: quay.io/containerbuildsystem/cachi2@sha256:e063d34694c74ac5ab57c8a0eaca7463d732d70778817545fa14f212416f31bf
    name: prefetch-dependencies
    env:
    - name: INPUT
      value: $(params.input)
    script: |
      if [ -z "${INPUT}" ]
      then
        echo "Build will be executed with network isolation, but no content was configured to be prefetched."
        exit 0
      fi

      cachi2 fetch-deps \
      --source=$(workspaces.source.path) \
      --output=$(workspaces.source.path)/cachi2/output \
      "${INPUT}"

      cachi2 generate-env $(workspaces.source.path)/cachi2/output \
      --format env \
      --for-output-dir=/cachi2/output \
      --output $(workspaces.source.path)/cachi2/cachi2.env

      cachi2 inject-files $(workspaces.source.path)/cachi2/output \
      --for-output-dir=/cachi2/output
  workspaces:
  - name: source
