apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build
  labels:
    "pipelines.openshift.io/used-by" : "build-cloud"
    "pipelines.openshift.io/runtime" : "generic"
    "pipelines.openshift.io/strategy" : "docker"
spec:
  params:
    - description: 'Source Repository URL'
      name: git-url
      type: string
    - description: 'Revision of the Source Repository'
      name: revision
      type: string
      default: main
    - description: 'Fully Qualified Output Image'
      name: output-image
      type: string
    - description: The path to your source code
      name: path-context
      type: string
      default: .
    - description: Path to the Dockerfile
      name: dockerfile
      type: string
      default: Dockerfile
  tasks:
    - name: appstudio-init
      params:
        - name: image-url
          value: "$(params.output-image)"
      taskRef:
        name: init
      workspaces:
        - name: source
          workspace: workspace
        - name: registry-auth
          workspace: registry-auth
    - name: clone-repository
      when:
      - input: $(tasks.appstudio-init.results.exists)
        operator: in
        values: ["false"]
      runAfter:
        - appstudio-init
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "$(params.revision)"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: appstudio-configure-build
      runAfter:
        - clone-repository
      when:
      - input: $(tasks.appstudio-init.results.exists)
        operator: in
        values: ["false"]
      taskRef:
        name: configure-build
      workspaces:
        - name: source
          workspace: workspace
        - name: registry-auth
          workspace: registry-auth
    - name: build-container
      params:
        - name: IMAGE
          value: >-
            $(params.output-image)
        - name: BUILDER_IMAGE
          value: >-
            registry.access.redhat.com/ubi8/buildah@sha256:31f84b19a0774be7cfad751be38fc97f5e86cefd26e0abaec8047ddc650b00bf
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.path-context)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: "$(tasks.appstudio-configure-build.results.buildah-auth-param)"
        - name: PUSH_EXTRA_ARGS
          value: "$(tasks.appstudio-configure-build.results.buildah-auth-param)"
      runAfter:
        - appstudio-configure-build
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: sanity-label-check
      runAfter:
        - build-container
      taskRef:
        name: sanity-label-check
      params:
      - name: sourceImage
        value: $(params.output-image)
    - name: show-summary
      runAfter:
        - build-container
      taskRef:
        name: summary
      params:
      - name: pipeline-run-name
        value: "$(context.pipelineRun.name)"
      - name: git-url
        value: "$(params.git-url)"
      - name: image-url
        value: $(params.output-image)
    - name: skip-rebuild-summary
      when:
      - input: $(tasks.appstudio-init.results.exists)
        operator: in
        values: ["true"]
      runAfter:
        - appstudio-init
      taskRef:
        name: summary
      params:
      - name: pipeline-run-name
        value: "$(context.pipelineRun.name)"
      - name: git-url
        value: "$(params.git-url)"
      - name: image-url
        value: $(params.output-image)
  workspaces:
    - name: workspace
    - name: registry-auth
      optional: true
    - name: git-auth
      optional: true
