apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: summary
spec:
  description: >-
    Summary Pipeline Task.
  params:
    - name: pipelinerun-name
      description: pipeline-run to annotate
    - name: git-url
      description: Git URL
    - name: image-url
      description: Image URL
  steps:
    - name: appstudio-summary
      image: registry.redhat.io/openshift4/ose-cli:v4.12@sha256:9f0cdc00b1b1a3c17411e50653253b9f6bb5329ea4fb82ad983790a6dbf2d9ad
      script: |
        #!/usr/bin/env bash
        echo
        echo "Build Summary:"
        echo
        echo "Build repository: $(params.git-url)"
        echo "Generated Image is in : $(params.image-url)"
        echo
        oc annotate --overwrite pipelinerun $(params.pipelinerun-name) build.appstudio.openshift.io/repo=$(params.git-url)
        oc annotate --overwrite pipelinerun $(params.pipelinerun-name) build.appstudio.openshift.io/image=$(params.image-url)
        echo End Summary

        oc delete --ignore-not-found=true secret $(params.pipelinerun-name)
