apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: appstudio-utils 
spec:
  description: >-
    Utilities 
  params:
    - name: SCRIPT
      description: Run a Script 
      default: "echo no-script-passed" 
  workspaces:
    - name: source
      optional: true
  steps:
    - name: script 
      image: quay.io/redhat-appstudio/appstudio-utils:v0.1
      script: |
        #!/bin/bash
        echo "App Studio Utility Task $(context.task.name)"     
        echo "$(params.SCRIPT)" | bash
